S2 offset
Open-EO/openeo-opensearch-client pull request #18
Opened 2023-06-16 09:31 UTC by EmileSonneveld

2023-06-19 13:39 UTC, JeroenVerstraelen requested changes

2023-06-19 14:37 UTC, EmileSonneveld commented on src/main/scala/org/openeo/opensearch/OpenSearchResponses.scala
> +        println("sdfdsf")
true, removed

2023-06-19 14:39 UTC, EmileSonneveld commented on src/main/scala/org/openeo/opensearch/OpenSearchResponses.scala
> +      throw new IllegalArgumentException("Use per band based pixelValueOffset instead!")
`pixelValueOffset` was only used shortly. I did a quick search trough gwc-geotrellis, BIGGEO and github and found no other references to `pixelValueOffset`

2023-06-20 08:41 UTC, JeroenVerstraelen approved these changes

2023-06-20 08:42 UTC, merged